### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by DarkC0der-0** [rodmontgt/udemy_dl#4]
root@DarkRoot:~/Desktop/udemy-dl-rs/udemy_dl# python -m udemy_dl https://www.udemy.com/thermodynamics-for-engineering-students/
Username / Email : ahmedyouness441@gmail.com
Password : 
[INFO-835] Downloading to: /root/Desktop/udemy-dl-rs/udemy_dl/thermodynamics-for-engineering-students

[INFO-107] Trying to log in ...
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/__main__.py", line 8, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 837, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 658, in udemy_dl
    login(username, password)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 109, in login
    csrf_token = get_csrf_token()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 102, in get_csrf_token
    return match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by obay** [comment]
Facing the same issue.

**Comment by zub3rrr** [comment]
same here

**Comment by huzaifasaeed123** [comment]
Same Issue
